#!/usr/bin/env python3
"""Report Generator Module"""
import json
import os
from datetime import datetime
from utils.logger import Logger

class ReportGenerator:
    def __init__(self, input_file: str, output: str, logger: Logger):
        self.input_file = input_file
        self.output = output
        self.logger = logger

    def run(self):
        self.logger.info(f"[*] Generating report from {self.input_file}")
        try:
            with open(self.input_file) as f:
                data = json.load(f)
        except Exception as e:
            self.logger.error(f"Failed to read input: {e}")
            return

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Shadow Attack Framework — Pentest Report</title>
    <style>
        body {{ font-family: monospace; background: #0d1117; color: #58a6ff; padding: 2em; }}
        h1 {{ color: #ff4444; }} h2 {{ color: #aaa; border-bottom: 1px solid #333; }}
        table {{ width:100%; border-collapse:collapse; }} td,th {{ border:1px solid #333; padding:8px; }}
        .success {{ color: #3fb950; }} .warning {{ color: #d29922; }} .danger {{ color: #f85149; }}
    </style>
</head>
<body>
    <h1>🔴 Shadow Attack Framework</h1>
    <h2>Penetration Test Report</h2>
    <p>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
    <h2>Findings</h2>
    <pre>{json.dumps(data, indent=2)}</pre>
    <hr>
    <p><small>Generated by Shadow Core | For authorized use only</small></p>
</body>
</html>"""

        with open(self.output, "w") as f:
            f.write(html)
        self.logger.success(f"[+] Report saved to {self.output}")
